create table IF NOT EXISTS CLIENTE(
    ID INT(3) AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CPF BIGINT(11) UNIQUE NOT NULL,
    PLACA VARCHAR(8) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    PRIMARY KEY(ID));